-- BetsPapa v1.21.0
-- PapaSense v2.0 — Four-Engine Resolution System
-- Run after BETSPAPA_V1_20_0_ATHENA_V3.sql.

begin;

create table if not exists public.engine_pick_results (
  id bigint generated by default as identity primary key,
  prediction_id bigint not null references public.predictions(id) on delete cascade,
  fixture_id bigint not null references public.fixtures(id) on delete cascade,
  league_id bigint references public.leagues(id) on delete cascade,
  engine_version text not null,
  engine_key text not null check (engine_key in ('primary', 'safer', 'aggressive', 'venue')),
  market_key text not null,
  market text,
  selection text not null,
  confidence numeric(8,4) not null default 0,
  outcome text not null check (outcome in ('WIN', 'LOSS', 'VOID')),
  graded_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (prediction_id, engine_key)
);

alter table public.engine_pick_results
  add column if not exists league_id bigint references public.leagues(id) on delete cascade;

create index if not exists engine_pick_results_calibration_idx
  on public.engine_pick_results (engine_version, engine_key, market_key, outcome);
create index if not exists engine_pick_results_fixture_idx
  on public.engine_pick_results (fixture_id);
create index if not exists engine_pick_results_league_idx
  on public.engine_pick_results (engine_version, league_id, engine_key, market_key, outcome);

create table if not exists public.engine_calibration_profiles (
  id bigint generated by default as identity primary key,
  engine_version text not null,
  engine_key text not null,
  market_key text not null,
  scope_key text not null default 'GLOBAL',
  league_id bigint references public.leagues(id) on delete cascade,
  sample_count integer not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  voids integer not null default 0,
  observed_hit_rate numeric(8,6) not null default 0,
  lower_bound numeric(8,6) not null default 0,
  brier_score numeric(8,6),
  last_calibrated_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (engine_version, engine_key, market_key, scope_key)
);

create index if not exists engine_calibration_profiles_lookup_idx
  on public.engine_calibration_profiles (engine_version, engine_key, market_key, scope_key);

alter table public.engine_pick_results enable row level security;
alter table public.engine_calibration_profiles enable row level security;

commit;
