-- BetsPapa v1.20.0
-- Athena v3.0.0 — Swing Resolution & Half-Goals Engine
-- Run once in Supabase SQL Editor before deploying the v1.20.0 backend.

begin;

create table if not exists public.fixture_goal_events (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null references public.fixtures(id) on delete cascade,
  external_fixture_id bigint not null,
  provider_event_key text not null,
  scoring_team_id bigint not null references public.teams(id) on delete cascade,
  provider_team_id bigint,
  minute integer not null default 0,
  extra_minute integer not null default 0,
  half smallint not null check (half in (1, 2)),
  time_bucket text not null,
  goal_type text,
  is_own_goal boolean not null default false,
  is_penalty boolean not null default false,
  home_score_before integer not null default 0,
  away_score_before integer not null default 0,
  home_score_after integer not null default 0,
  away_score_after integer not null default 0,
  match_state_before text not null,
  match_state_after text not null,
  is_equaliser boolean not null default false,
  is_lead_goal boolean not null default false,
  is_comeback_goal boolean not null default false,
  is_winning_goal_after_equalising boolean not null default false,
  raw_event jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (fixture_id, provider_event_key)
);

create index if not exists fixture_goal_events_fixture_idx
  on public.fixture_goal_events (fixture_id, minute, extra_minute);
create index if not exists fixture_goal_events_team_idx
  on public.fixture_goal_events (scoring_team_id, half, minute);

create table if not exists public.fixture_event_coverage (
  fixture_id bigint primary key references public.fixtures(id) on delete cascade,
  external_fixture_id bigint not null,
  status text not null check (status in ('COMPLETE', 'PARTIAL', 'UNAVAILABLE')),
  goals_expected integer not null default 0,
  goals_recorded integer not null default 0,
  last_attempted_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists fixture_event_coverage_status_idx
  on public.fixture_event_coverage (status, last_attempted_at);

create table if not exists public.team_half_goal_profiles (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  league_id bigint not null references public.leagues(id) on delete cascade,
  season integer not null,
  scope text not null,
  matches_played integer not null default 0,
  first_half_goals_for integer not null default 0,
  first_half_goals_against integer not null default 0,
  second_half_goals_for integer not null default 0,
  second_half_goals_against integer not null default 0,
  first_half_scoring_rate numeric(8,6) not null default 0,
  first_half_conceding_rate numeric(8,6) not null default 0,
  second_half_scoring_rate numeric(8,6) not null default 0,
  second_half_conceding_rate numeric(8,6) not null default 0,
  first_half_over_05_rate numeric(8,6) not null default 0,
  first_half_over_15_rate numeric(8,6) not null default 0,
  second_half_over_05_rate numeric(8,6) not null default 0,
  second_half_over_15_rate numeric(8,6) not null default 0,
  scored_both_halves_rate numeric(8,6) not null default 0,
  goals_both_halves_rate numeric(8,6) not null default 0,
  second_half_win_rate numeric(8,6) not null default 0,
  second_half_draw_rate numeric(8,6) not null default 0,
  event_coverage_matches integer not null default 0,
  goals_while_trailing integer not null default 0,
  equalisers_scored integer not null default 0,
  winning_goals_after_equalising integer not null default 0,
  leads_surrendered integer not null default 0,
  minute_46_60_for integer not null default 0,
  minute_46_60_against integer not null default 0,
  minute_61_75_for integer not null default 0,
  minute_61_75_against integer not null default 0,
  minute_76_90_for integer not null default 0,
  minute_76_90_against integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (team_id, league_id, season, scope)
);

create index if not exists team_half_goal_profiles_lookup_idx
  on public.team_half_goal_profiles (team_id, league_id, season, scope);

alter table public.fixture_goal_events enable row level security;
alter table public.fixture_event_coverage enable row level security;
alter table public.team_half_goal_profiles enable row level security;

commit;
