-- BetsPapa v1.25.0
-- PapaLock Banker Engine v1.0
-- Run after BETSPAPA_V1_21_0_PAPASENSE_V2.sql and BETSPAPA_V1_23_0_COMPETITION_AND_HALF_MARKET_GUARDS.sql.

begin;

create table if not exists public.papalock_predictions (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null references public.fixtures(id) on delete cascade,
  external_fixture_id text,
  prediction_date date not null,
  league_id bigint references public.leagues(id) on delete cascade,
  source_prediction_id bigint references public.predictions(id) on delete set null,
  engine_version text not null,
  market_key text not null,
  market text not null,
  selection text not null,
  story text not null,
  banker_score numeric(8,4) not null default 0,
  grade text not null check (grade in ('ELITE', 'PRIME', 'QUALIFIED', 'WITHHELD')),
  confirmation_families integer not null default 0,
  status text not null default 'PENDING' check (status in ('PENDING', 'WIN', 'LOSS', 'VOID')),
  published boolean not null default false,
  public_explanation text,
  evidence jsonb not null default '{}'::jsonb,
  internal_audit jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (fixture_id, engine_version, prediction_date)
);

create index if not exists papalock_predictions_date_idx
  on public.papalock_predictions (prediction_date, published, banker_score desc);
create index if not exists papalock_predictions_league_idx
  on public.papalock_predictions (league_id, prediction_date);
create index if not exists papalock_predictions_story_idx
  on public.papalock_predictions (engine_version, story, status);

create table if not exists public.papalock_engine_evidence (
  id bigint generated by default as identity primary key,
  papalock_prediction_id bigint not null references public.papalock_predictions(id) on delete cascade,
  family_key text not null check (family_key in ('papasense', 'venue', 'athena')),
  family_name text not null,
  confidence numeric(8,4) not null default 0,
  evidence_strength numeric(8,6) not null default 0,
  contributing_picks jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  unique (papalock_prediction_id, family_key)
);

create index if not exists papalock_engine_evidence_prediction_idx
  on public.papalock_engine_evidence (papalock_prediction_id, family_key);

create table if not exists public.papalock_results (
  id bigint generated by default as identity primary key,
  papalock_prediction_id bigint not null references public.papalock_predictions(id) on delete cascade,
  fixture_id bigint not null references public.fixtures(id) on delete cascade,
  league_id bigint references public.leagues(id) on delete cascade,
  engine_version text not null,
  story text not null,
  market_key text not null,
  selection text not null,
  banker_score numeric(8,4) not null default 0,
  outcome text not null check (outcome in ('WIN', 'LOSS', 'VOID')),
  halftime_score text,
  fulltime_score text,
  graded_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (papalock_prediction_id)
);

create index if not exists papalock_results_calibration_idx
  on public.papalock_results (engine_version, story, league_id, outcome);
create index if not exists papalock_results_fixture_idx
  on public.papalock_results (fixture_id);

create table if not exists public.papalock_calibration_profiles (
  id bigint generated by default as identity primary key,
  engine_version text not null,
  story text not null,
  scope_key text not null default 'GLOBAL',
  league_id bigint references public.leagues(id) on delete cascade,
  sample_count integer not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  voids integer not null default 0,
  observed_hit_rate numeric(8,6) not null default 0,
  lower_bound numeric(8,6) not null default 0,
  brier_score numeric(8,6),
  last_calibrated_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (engine_version, story, scope_key)
);

create index if not exists papalock_calibration_lookup_idx
  on public.papalock_calibration_profiles (engine_version, story, scope_key);

alter table public.papalock_predictions enable row level security;
alter table public.papalock_engine_evidence enable row level security;
alter table public.papalock_results enable row level security;
alter table public.papalock_calibration_profiles enable row level security;

commit;
